[build-system]
requires = ["setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name = "pygpsclient"
authors = [
    {name = "semuadmin", email = "semuadmin@semuconsulting.com"},
]
maintainers = [
  {name = "semuadmin", email = "semuadmin@semuconsulting.com"}
]
description = "GNSS Diagnostic and UBX Configuration GUI Application"
version = "1.3.21"
license = {file = "LICENSE"}
keywords= [
    "PyGPSClient",
    "GNSS",
    "GPS",
    "GALILEO",
    "GLONASS",
    "BEIDOU",
    "NMEA",
    "UBX",
    "RTCM",
    "NTRIP",
    "SPARTN",
    "RTK",
    "DGPS",
    "u-center",
    ]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Environment :: MacOS X",
    "Environment :: Win32 (MS Windows)",
    "Environment :: X11 Applications",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: GIS",
    ]

dependencies = [
    "pygnssutils>=1.0.5",
    "requests>=2.28.0",
    "Pillow>=9.0.0",
    "pyserial>=3.5",
    "pyspartn>=0.1.3",
    "geographiclib>=2.0",
]

[project.scripts]
pygpsclient = "pygpsclient.__main__:main"

[project.urls]
homepage = "https://www.semuconsulting.com/pygpsclientgui"
documentation = "https://www.semuconsulting.com/pygpsclient/"
repository = "https://github.com/semuconsulting/PyGPSClient"
changelog = "https://github.com/semuconsulting/PyGPSClient/blob/master/RELEASE_NOTES.md"

[project.optional-dependencies]
test = [
    "black>=23.1",
    "pylint>=2.17",
    "coverage>=7.2",
    "Sphinx>=6.1.3",
    "sphinx-rtd-theme>=1.2.0",
]
