name: pygpsclient

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build dependencies
        run: |
          if [ -f requirements_build.txt ]; then pip install -r requirements_build.txt; fi
      - name: Install code dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with pylint
        run: |
          pylint -E src/pygpsclient
      - name: Security vulnerability analysis with bandit
        run: |
          python bandit -c pyproject.toml -r -lll .
      - name: Test with pytest
        run: |
          pytest
